sudo: required
services:
  - docker

before_install:
  - docker build -t yongmkkk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yongmkkk/react-test npm test

after_success:
  - docker build -t yongmkkk/multi-client ./client
  - docker build -t yongmkkk/multi-nginx ./nginx
  - docker build -t yongmkkk/multi-server ./server
  - docker build -t yongmkkk/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push yongmkkk/multi-client
  - docker push yongmkkk/multi-nginx
  - docker push yongmkkk/multi-server
  - docker push yongmkkk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-76584358004'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY